version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - my-network

  dotnet-sdk-8:
    image: mcr.microsoft.com/dotnet/sdk:8
    volumes:
      - .:/app
    working_dir: /src
    ports:
      - "5000:5000"
    depends_on:
      - sql-server
    networks:
      - my-network

networks:
  my-network:
